name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Test install Neovim
      run: brew install --HEAD neovim
    - name: Install vim-plug
      run: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    - name: Test nvim version
      run: nvim -v
